[package]
name = "code_forces"
version = "0.1.0"
authors = ["Michał Kalbarczyk <fazibear@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
